house/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('create/house<int:pk>', views.create_house, name='create_house'),
    path('create/apartment/<int:pk>', views.create_apartment, name='create_apartment'),
    path('chat/<int:pk>', views.chat, name='chat'),
    path('chats/', views.chats, name='chats')

]

nedviga/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('house.urls', 'nedviga'), namespace='house')),
    path('auth/', include(('users.urls', 'nedviga'), namespace='auth')),
    # path('oauth/', include('social_django.urls', namespace='social')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.sign_in, name='login'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.out, name='logout')
]

house/models.py
from django.contrib.auth.models import User
from django.db.models import *

Material_choise = [
    ('дерево', 'дерево'),
    ('кирпич', 'кирпич'),
    ('керамические блоки', 'керамические блоки'),
    ('газобетон', 'газобетон'),
]

Type_choise = [
    ('дом', 'дом'),
    ('квартира', 'квартира'),
    ('земельный участок', 'земельный участок'),

]

Furniture = [
    ('С мебелью', 'С мебелью'),
    ('Без мебели', 'Без мебели'),
    ('Частично', 'Частично'),
    ('Только кухня', 'Только кухня'),
    ('Только санузел', 'Только санузел'),
]

Repair = [
    ('Евро ремонт', 'Евро ремонт'),
    ('Черновая отделка', 'Черновая отделка'),
    ('Без ремонта', 'Без ремонта'),
    ('Частичная отделка', 'Частичная отделка'),
]

Building_type = [
    ('Панельный дом', 'Панельный дом'),
    ('Кирпичный дом', 'Кирпичный дом'),
    ('Монолитный дом', 'Монолитный дом'),
    ('Блочный дом', 'Блочный дом'),
    ('Деревянный дом', 'Деревянный дом'),
]

Housing_type = [
    ('Вторичный рынок', 'Вторичный рынок'),
    ('Новостройка', 'Новостройка'),
]

Layout = [
    ('Смежная', 'Смежная'),
    ('Раздельная', 'Раздельная'),
    ('Смежно-раздельная', 'Смежно-раздельная'),
    ('Студия', 'Студия'),
    ('Пентхаус', 'Пентхаус'),
    ('Многоуровневая', 'Многоуровневая'),
    ('Малосемейка', 'Малосемейка'),
]

Location = [
    ('В городе', 'В городе'),
    ('Пригород', 'Пригород'),
    ('За городом', 'За городом'),
]


class House(Model):
    type = CharField(max_length=25, choices=Type_choise, null=True)
    housing_type = CharField(max_length=25, choices=Housing_type, null=True)
    title = CharField(max_length=255)
    bio = TextField()
    address = CharField(max_length=255)
    preview = ImageField(null=True, blank=True)
    price = IntegerField()
    size = IntegerField()
    material = CharField(max_length=255, choices=Material_choise, null=True)
    rooms = IntegerField()
    furniture = CharField(max_length=20, choices=Furniture, null=True)
    repair = CharField(max_length=20, choices=Repair, null=True)
    near = TextField(null=True, blank=True)
    date_of_building = IntegerField(max_length=4, null=True, blank=True)
    seller = ForeignKey(User, on_delete=CASCADE, null=True)
    address = CharField(max_length=255, null=True)
    number = IntegerField(default=0, null=True)
    date_added = DateTimeField(null=True, auto_now_add=True)
    convenience = TextField(null=True)
    rent = BooleanField(default=False, null=True)
    living_space = IntegerField(null=True)
    ceiling_height = IntegerField(default=2, null=True)
    #################
    floor = IntegerField(null=True, blank=True)
    storeys = IntegerField(null=True, blank=True)
    building_type = CharField(max_length=20, choices=Building_type, null=True)
    layout = CharField(max_length=34, choices=Layout, null=True)
    #################
    location = CharField(max_length=20, choices=Location, null=True)

    def __str__(self):
        return str(self.pk)

    def home_title(self):
        return self.title[:20]


class Image(Model):
    house = ForeignKey(House, on_delete=CASCADE, related_name='house')
    image1 = ImageField(blank=True)
    image2 = ImageField(blank=True)
    image3 = ImageField(blank=True)
    image4 = ImageField(blank=True)
    image5 = ImageField(blank=True)
    image6 = ImageField(blank=True)
    image7 = ImageField(null=True)
    image8 = ImageField(null=True)
    image9 = ImageField(null=True)
    image10 = ImageField(null=True)
    image11 = ImageField(null=True)
    image12 = ImageField(null=True)
    image13 = ImageField(null=True)
    image14 = ImageField(null=True)
    image15 = ImageField(null=True)
    image16 = ImageField(null=True)

    def __str__(self):
        return str(self.house)


class Message(Model):
    text = CharField(max_length=100000)
    sender = ForeignKey(User, on_delete=CASCADE,related_name='sender')
    receiver = ForeignKey(User, on_delete=CASCADE,related_name='receiver')
    time = DateTimeField(auto_now_add=True)
    house = ForeignKey(House, on_delete=CASCADE, null=True)
    chat = ForeignKey('house.Chat', on_delete=CASCADE, null=True)

    def __str__(self):
        return self.text[:20]


class Chat(Model):
    sender = ForeignKey(User, on_delete=CASCADE, related_name='sender1')
    receiver = ForeignKey(User, on_delete=CASCADE, related_name='receiver1')
    time = DateTimeField(auto_now_add=True)
    house = ForeignKey(House, on_delete=CASCADE, null=True)

    def __str__(self):
        return str(self.pk)

users/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, )
    register_at = models.DateTimeField(auto_now_add=True)
    avatar = models.ImageField(blank=True, null=True, default='avatar.png')
    full_name = models.CharField(max_length=255)

    def __str__(self):
        return self.full_name

house/forms.py
from django import forms
from .models import *


class BaseForm(forms.ModelForm):
    type = forms.ChoiceField(choices=Type_choise, label='Выберите тип дома')
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}), label='Введите заголовок')
    bio = forms.CharField(widget=forms.Textarea(), label='Опишите ваш дом')
    preview = forms.ImageField(widget=forms.FileInput(attrs={'class': 'input'}), label='Главное фото')
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}), label='Введите адрес')
    price = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input has-text-centered'}), label='Цена')
    size = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input has-text-centered'}), label='Размер')
    material = forms.ChoiceField(choices=Material_choise, label='Материал')
    rooms = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input has-text-centered', 'maxlength': '3',
                                                               'oninput': 'javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength)'}),
                               label='Количество комнат')
    furniture = forms.ChoiceField(choices=Furniture, label='Мебилизаация')
    repair = forms.ChoiceField(choices=Repair, label='Тип ремонта')
    near = forms.CharField(widget=forms.Textarea(), label='Что есть рядом')
    date_of_building = forms.IntegerField(
        widget=forms.NumberInput(attrs={'maxlength': '4',
                                        'oninput': 'javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength)'}),
        label='Дата постройки'),
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}), label='Адрес')
    number = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input has-text-centered'}),
                                label='Номер телефона')
    housing_type = forms.ChoiceField(choices=Housing_type, label='Выберите тип строения')
    ceiling_height = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input has-text-centered'}),
                                        label='Высота потолков')
    living_space = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input'}), label='Жилая площадь')
    rent = forms.BooleanField(widget=forms.CheckboxInput(), label='В аренду')

    class Meta:
        model = House
        fields = [
            'type', 'title', 'bio', 'preview', 'address',
            'price',
            'size', 'material', 'rooms', 'furniture', 'repair',
            'near', 'date_of_building', 'number', 'housing_type', 'ceiling_height', 'living_space',
            'rent']


class ApartamentForm(forms.ModelForm):
    floor = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input'}), label='Этаж')
    storeys = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input'}), label='Этажность дома')
    building_type = forms.ChoiceField(choices=Building_type, label='Тип строения')
    layout = forms.ChoiceField(choices=Layout, label='Планировка')

    class Meta:
        model = House
        fields = ['floor', 'storeys', 'building_type', 'layout']


class HouseForm(forms.ModelForm):
    location = forms.ChoiceField(choices=Location, label='Локация')
    convenience = forms.CharField(widget=forms.Textarea(), label='Удобства')

    class Meta:
        model = House
        fields = ['location', 'convenience']


class CustomFileField(forms.FileInput):
    template_name = 'file.html'


class ImageForm(forms.ModelForm):
    image1 = forms.ImageField()
    image2 = forms.ImageField()
    image3 = forms.ImageField()
    image4 = forms.ImageField()
    image5 = forms.ImageField()
    image6 = forms.ImageField()
    image7 = forms.ImageField()
    image8 = forms.ImageField()
    image9 = forms.ImageField()
    image10 = forms.ImageField()
    image11 = forms.ImageField()
    image12 = forms.ImageField()
    image13 = forms.ImageField()
    image14 = forms.ImageField()
    image15 = forms.ImageField()
    image16 = forms.ImageField()

    class Meta:
        model = Image
        fields = ['image1', 'image2', 'image3', 'image4', 'image5', 'image6',
                  'image7', 'image8', 'image9', 'image10', 'image11', 'image12', 'image13', 'image14', 'image15',
                  'image16', ]


class MessageForm(forms.ModelForm):
    text = forms.CharField(widget=forms.TextInput())

    class Meta:
        model = Message
        fields = [
            'text'
        ]

users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class UserCreationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}), label='Придумайте никнейм')
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}), label='Придумайте пароль')
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}), label='Повторите пароль')

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class ProfileForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}), label='Введите ваше имя')
    avatar = forms.ImageField(widget=forms.FileInput(), label='Выберите фото профиля')

    class Meta:
        model = Profile
        fields = ['full_name', 'avatar']


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}), label='Никнейм')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}), label='Пароль')

    class Meta:
        model = User
        fields = ['username', 'password']

house/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth.decorators import login_required
from .models import *


def home(request):
    houses = House.objects.all().order_by('-date_added')
    return render(request, 'home.html', {'houses': houses})


@login_required(login_url='/auth/login/')
def create(request):
    form = BaseForm(request.POST, request.FILES)
    image_form = ImageForm(request.POST, request.FILES)
    if request.method == 'POST':
        if form.is_valid():
            dom = House.objects.create(seller=request.user, **form.cleaned_data)
            if image_form.is_valid():
                a = image_form.save(commit=False)
                a.house = dom
                a.save()
        if dom.type == 'квартира':
            return redirect('house:create_apartment', dom.pk)
        if dom.type == 'дом':
            return redirect('house:create_house', dom.pk)
    return render(request, 'create.html', {'form': form, 'form2': image_form})


def create_apartment(request, pk):
    house = House.objects.get(pk=pk)
    form = ApartamentForm(request.POST, instance=house)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('house:home')
    return render(request, 'create_apartament.html', {'form': form})


def create_house(request, pk):
    house = House.objects.get(pk=pk)
    form = HouseForm(request.POST, instance=house)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('house:home')
    return render(request, 'create_house.html', {'form': form})


def detail(request, pk):
    house = House.objects.get(pk=pk)
    images = Image.objects.filter(house=house)
    receiver = house.seller
    sender = request.user
    form = MessageForm(request.POST)
    if request.method == 'POST' and form.is_valid():
        chat = Chat.objects.create(sender=sender, receiver=receiver, house=house)
        message = Message.objects.create(sender=sender, house=house, receiver=receiver, chat=chat, **form.cleaned_data)
        return redirect('house:detail', house.pk)
    return render(request, 'detail.html', {'house': house, 'images': images, 'form': form})




def chat(request, pk):
    chat = Chat.objects.get(pk=pk)
    sender = request.user
    receiver = chat.receiver
    form = MessageForm(request.POST)
    if request.method == 'POST' and form.is_valid():
        message = Message.objects.create(sender=sender, receiver=receiver,chat=chat, **form.cleaned_data)
        return redirect('house:chat', chat.pk)
    messages = Message.objects.filter(chat=chat)
    return render(request, 'chat.html', {'form': form,'messages':messages})


def chats(request):
    chats = Chat.objects.filter(sender=request.user,) | Chat.objects.filter(receiver=request.user)
    return render(request, 'chats.html', {'chats': chats})

users/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth import login, logout


def register(request):
    user_form = UserCreationForm(request.POST)
    profile_form = ProfileForm(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if user_form.is_valid():
            user = user_form.save()
            if profile_form.is_valid():
                Profile.objects.create(user=user, **profile_form.cleaned_data)
                return redirect('auth:login')
    return render(request, 'register.html', {'user_form': user_form, 'profile_form': profile_form})


def sign_in(request):
    form = LoginForm(data=request.POST or None)
    if request.method == 'POST' and form.is_valid():
        user = form.get_user()
        login(request, user)
        return redirect('house:home')
    errors = form.errors.as_data()
    return render(request, 'login.html', {'form': form, 'errors':errors})


def profile(request):
    profile = Profile.objects.get(user=request.user)
    return render(request, 'profile.html', {'profile': profile})


def out(request):
    logout(request)
    return redirect('house:home')

house/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link rel='icon' href='{% static '25694.png' %}' type='image/x-icon'>
</head>
<body>
<nav class="navbar background-light-sea">
    <a href="{% url 'house:home' %}" class="nav-item">Главная</a>
    <a href="{% url 'house:create' %}" class="nav-item">Добавить объявление</a>
    {% if user.is_authenticated %}
        <a href="{% url 'auth:logout' %}" class="nav-item">Выход</a>
        <a href="{% url 'auth:profile' %}" class="nav-item"><img height="50" width="50"
                                                                 style="border-radius: 50%; border: 1px solid grey"
                                                                 src="{{ user.profile.avatar.url }}" alt=""></a>
    {% else %}
        <a href="{% url 'auth:register' %}" class="nav-item">Зарегистрироваться</a>
        <a href="{% url 'auth:login' %}" class="nav-item">Войти</a>
    {% endif %}
</nav>
{% block content %}
{% endblock %}
{% block script %}
{% endblock %}
<script src="{% static 'carousel.js' %}"></script>
<script src="{% static 'select.js' %}"></script>
</body>
</html>

house/templates/chat.html
{% extends 'base.html' %}
{% block content %}
{% for a in messages %}
    <h1>{{ a.sender.profile.full_name }}</h1>
    <h1>{{ a.receiver.profile.full_name }}</h1>
    <h1>{{ a.text }}</h1>
{% endfor %}
    <form method="post" action="">
            {% csrf_token %}
            {{ form }}
            <button type="submit">Ho</button>
        </form>
{% endblock %}

house/templates/chats.html
{% extends 'base.html' %}
{% block content %}
{% for chat in chats %}
    <div style="border: 1px solid black">
    <a href="{% url 'house:chat' chat.pk %}">
        <h1>{{ chat.house }}</h1>
        <h1>{{ chat.sender }}</h1>
        <h1>{{ chat.receiver }}</h1>
    </a>
    </div>
{% endfor %}

{% endblock %}

house/templates/create.html
{% extends 'base.html' %}
{% block content %}
        <form class="form" method="post" enctype="multipart/form-data" action="">
            {% csrf_token %}
            {% for field in form %}
                <div class="field">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                </div>
            {% endfor %}
            <button class="button background-light-sea" type="submit">Дальше</button>
        </form>
{% endblock %}

house/templates/create_apartament.html
{% extends 'base.html' %}
{% block content %}
        <form class="form"  method="post" action="">
            {% csrf_token %}
            {% for field in form %}
            <div class="field">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
            </div>
            {% endfor %}
        <button class="button background-light-sea" type="submit">Создать</button>
        </form>
{% endblock %}

house/templates/create_house.html
{% extends 'base.html' %}
{% block content %}
        <form class="form"  method="post" action="">
            {% csrf_token %}
            {% for field in form %}
            <div class="field">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
            </div>
            {% endfor %}
        <button class="button background-light-sea" type="submit">Создать</button>
        </form>
{% endblock %}

house/templates/detail.html
{% extends 'base.html' %}
{% block title %}
    {{ house.title }}
{% endblock %}
{% block content %}
    <div class="section">
        <h1 class="title is-1 text-centered">{{ house.title }}</h1>
        <div class="slideshow-container">
            {% for image in images %}
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image1.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image2.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image3.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image4.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image5.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image5.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image6.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image7.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image8.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image9.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image10.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image11.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image12.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image13.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image14.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image15.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image16.url }}" alt="">
                </div>
            {% endfor %}
            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
            <a class="next" onclick="plusSlides(1)">&#10095;</a>
        </div>
        <div class="about">
            <div class="border">
                Тип жилья: {{ house.type }}
            </div>
            <div class="border">
                Цена: {{ house.price }}
            </div>
            <div class="border">
                Размер дома: {{ house.size }}
            </div>
            <div class="border">
                Материал: {{ house.material }}
            </div>
            <div class="border">
                Количество комнат: {{ house.rooms }}
            </div>
            <div class="border">
                Мебилизация: {{ house.furniture }}
            </div>
            <div class="border">
                Ремонт: {{ house.repair }}
            </div>
            <div class="border">
                Дата постройки: {{ house.date_of_building }}
            </div>
            <div class="border">
                Поблизости: {{ house.near }}
            </div>

            {% if house.type == 'квартира' %}
                <div class="border">
                    Этаж: {{ house.floor }}
                </div>
                <div class="border">
                    Этажность дома: {{ house.storeys }}
                </div>
                <div class="border">
                    Тип строения: {{ house.building_type }}
                </div>
            {% endif %}
            {% if house.type == 'дом' %}
                <div class="border">
                    Жилая площадь: {{ house.living_space }}
                </div>
                <div class="border">
                    Местонахождение: {{ house.location }}
                </div>
                <div class="border">
                    Удобства: {{ house.convenience }}
                </div>
            {% endif %}
        </div>
        <div class="title is-1">Описание</div>
        <br>
        <div class="desk">
            {{ house.bio }}
        </div>
        <form method="post" action="">
            {% csrf_token %}
            {{ form }}
            <button type="submit">Ho</button>
        </form>
    </div>
{% endblock %}

house/templates/file.html
<div class="modal-item">
    <label class="label-create">
        <input style="border: none;width: 100%" type="{{ widget.type }}" class="input" name="{{ widget.name }}"
                {% if widget.value != None %}
               value="{{ widget.value|stringformat:'s' }}"
                {% endif %}
                {% include "django/forms/widgets/attrs.html" %}>
        <span class="file-box">
               <span class="label-create">
                   Choose a file…
               </span>
           </span>
    </label>
</div>

house/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Главная
{% endblock %}
{% block add %}

{% endblock %}
{% block content %}
    <div class="section">
        <div class="columns">
            {% for house in houses %}
                <div class="card">
                    <a href="{% url 'house:detail' house.pk %}">
                        <div class="image">
                        <img width="100%" height="100%" src="{{ house.preview.url }}" alt="">
                    </div>
                    <div class="title is-fixed is-3 text-centered">
                        {{ house.home_title }}...
                    </div>
                    <div class="title is-4">
                        {{ house.price }} sum
                    </div>
                    <div class="title is-6">
                        На сайте с: {{ house.date_added }}
                    </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

house/templates/type.html
<input class="modal-btn" type="checkbox" id="modal-btn" name="modal-btn"/>
<label for="modal-btn">Выбрать</label>
<div class="modal">
    <div class="modal-wrap">
        {% for a in type %}
            <a class="modal-item" href="{% url 'house:home' %}?type={{ a }}">{{ a }}</a>
        {% endfor %}
    </div>
</div>

house/templates/users.html
{% extends 'base.html' %}

{% block content %}
<ul>
{% for user in users %}
    <a href="{% url 'house:chat' user.pk %}">
        <li>{{ user.profile.full_name }}</li>
    </a>
{% endfor %}

</ul>
{% endblock %}